export const LOGIN_ACTION_TYPES = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FULFILLED: "LOGIN_FULFILLED",
    LOGIN_REJECTED: "LOGIN_REJECTED"
};

export const GET_DATA_ACTION_TYPES = {
    GET_DATA_REQUEST: "GET_DATA_REQUEST",
    GET_DATA_FULFILLED: "GET_DATA_FULFILLED",
    GET_DATA_REJECTED: "GET_DATA_REJECTED"
};

export const SAVE_DATA_ACTION_TYPES = {
    SAVE_DATA_REQUEST: "SAVE_DATA_REQUEST",
    SAVE_DATA_FULFILLED: "SAVE_DATA_FULFILLED",
    SAVE_DATA_REJECTED: "SAVE_DATA_REJECTED"
};

export const SAVE_CATEGORY_ACTION_TYPES = {
    SAVE_CATEGORY_REQUEST: "SAVE_CATEGORY_REQUEST",
    SAVE_CATEGORY_FULFILLED: "SAVE_CATEGORY_FULFILLED",
    SAVE_CATEGORY_REJECTED: "SAVE_CATEGORY_REJECTED"
};

export const GET_CATEGORY_ACTION_TYPES = {
    GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
    GET_CATEGORY_FULFILLED: "GET_CATEGORY_FULFILLED",
    GET_CATEGORY_REJECTED: "GET_CATEGORY_REJECTED"
};

export const UPDATE_DATA_ACTION_TYPES = {
    UPDATE_DATA_REQUEST: "UPDATE_DATA_REQUEST",
    UPDATE_DATA_FULFILLED: "UPDATE_DATA_FULFILLED",
    UPDATE_DATA_REJECTED: "UPDATE_DATA_REJECTED"
};

export const DELETE_DATA_ACTION_TYPES = {
    DELETE_DATA_REQUEST: "DELETE_DATA_REQUEST",
    DELETE_DATA_FULFILLED: "DELETE_DATA_FULFILLED",
    DELETE_DATA_REJECTED: "DELETE_DATA_REJECTED"
};